name: Build/release Neo Media Player Electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build Capacitor App
        run: bash build_electron.sh

      - name: Upload artifacts to
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: |
            ./electron/dist/