name: Build/release Neo Media Player Electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build Capacitor App
        run: |
          npm i
          npm run build-capacitor-electron

      - name: Build Electron app
        run: |
          cd electron
          npm i
          npm run electron:pack
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} npm run electron:make
          cd ..