name: Build/release Neo Media Player Electron

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build Capacitor App
        run: |
          npm i
          npm run build-capacitor-electron

      - name: Build Electron app
        run: |
          cd electron
          npm i
          npm run build electron:make

      - name: Upload artifacts to
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: electron/dist/